### ISSUE TITLE
Plugin does not run in official Verdaccio docker image

### ISSUE THREAD

**Issue by esmiralha** [SzymonDukla/verdaccio-gitlab-oauth2#3]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |   verdaccio/verdaccio:5      |
| verdaccio-gitlab-oauth2 |     1.0.10    |

#### Expected behavior
Given a Dockerfile:

```
FROM verdaccio/verdaccio:5 as builder
USER root
ENV NODE_ENV=production
RUN npm install --global-style verdaccio-gitlab-oauth2
RUN npm install --global-style verdaccio-aws-s3-storage

FROM verdaccio/verdaccio:5

ENV NODE_ENV=production
COPY ./config.yaml /verdaccio/conf/
COPY --from=builder --chown=$VERDACCIO_USER_UID:root /opt/verdaccio/node_modules/verdaccio-aws-s3-storage /verdaccio/plugins/verdaccio-aws-s3-storage/
COPY --from=builder --chown=$VERDACCIO_USER_UID:root /opt/verdaccio/node_modules/verdaccio-gitlab-oauth2 /verdaccio/plugins/verdaccio-gitlab-oauth2/
```
When I build an image and run a container out of it, 
Then the plugin should be found and loaded

#### Observed behaviour

Plugin fails to be found:
 ```
warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: verdaccio-aws-s3-storage
(node:7) Warning: deprecate: multiple logger configuration is deprecated, please check the migration guide.
(Use `node --trace-warnings ...` to show where the warning was created)
 error--- plugin not found. try npm install verdaccio-gitlab-oauth2
(node:7) UnhandledPromiseRejectionWarning: Error:
        verdaccio-gitlab-oauth2 plugin not found. try "npm install verdaccio-gitlab-oauth2"
    at /opt/verdaccio/build/lib/plugin-loader.js:110:13
    at Array.map (<anonymous>)
    at loadPlugin (/opt/verdaccio/build/lib/plugin-loader.js:62:37)
    at Auth._loadPlugin (/opt/verdaccio/build/lib/auth.js:56:38)
    at new Auth (/opt/verdaccio/build/lib/auth.js:46:25)
    at defineAPI (/opt/verdaccio/build/api/index.js:43:16)
    at _default (/opt/verdaccio/build/api/index.js:124:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce
1. `docker build -t verdaccio-custom .`
2. `docker run -it --rm -p 4873:4873 --env-file env.list --name verdaccio verdaccio-custom`

**Comment by paydaycay** [comment]
Hi @esmiralha and @SzymonDukla , I'm facing the same issue.
After investigations, the dist/public directory does not contain verdaccio-5.js.
I guess that's why the plugin is not found by Verdaccio.
How can we fix it ?

**Comment by aol-nnov** [comment]
Hi @SzymonDukla ! Any estimates on publishinging this fix to the npm registry?
